configuration:
  swagger:
    app: 'Movie System'
    description: 'A mini Netflix built with Spring Boot'
    developer: 'Arijan Komsic'
    email: 'arijan.komsic@stu.ibu.edu.ba'

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library