configuration:
  swagger:
    app: 'Movie System'
    description: 'A mini Netflix built with Spring Boot'
    developer: 'Arijan Komsic'
    email: 'arijan.komsic@stu.ibu.edu.ba'

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library

security:
  jwt:
    secret: 'fjWhWmSuM4hby0GbwrV9NchFEF4Gu24kfi8TbFLDeBYD68ez9aLtNUaBVMDiA1Yd'